### ISSUE TITLE
一直处于‘初始化软件源’

### ISSUE THREAD

**Issue by vavo-cake** [summerblue/laravel-ubuntu-init#16]
是以 root 身份运行，但是现在一直处于 `正在初始化软件源 -{PATH}` 这个位置

**Comment by leo108** [comment]
把 `/var/log/laravel-ubuntu-init.log` 这个文件内容贴出来，看看是否有报错

**Comment by Tex007** [comment]
用的是国外的服务器linode,也是这个问题,处在正在初始化软件源

**Comment by Tex007** [comment]
用的是国外的服务器linode,也是这个问题,处在正在初始化软件源

**Comment by Tex007** [comment]
国内的阿里云很快就装好了

**Comment by Tex007** [comment]
Generating locales (this might take a while)...
  en_US.UTF-8... done
Generation complete.
Generating locales (this might take a while)...
  zh_CN.UTF-8... done
Generation complete.
Hit:1 http://mirrors.linode.com/ubuntu xenial InRelease
Get:2 http://mirrors.linode.com/ubuntu xenial-updates InRelease [109 kB]
Get:3 http://mirrors.linode.com/ubuntu xenial-backports InRelease [107 kB]
Get:4 http://security.ubuntu.com/ubuntu xenial-security InRelease [107 kB]
Get:5 http://mirrors.linode.com/ubuntu xenial-updates/main amd64 Packages [825 kB]
Get:6 http://mirrors.linode.com/ubuntu xenial-updates/main i386 Packages [750 kB]
Get:7 http://mirrors.linode.com/ubuntu xenial-updates/main Translation-en [339 kB]
Get:8 http://mirrors.linode.com/ubuntu xenial-updates/restricted amd64 Packages [7,556 B]
Get:9 http://mirrors.linode.com/ubuntu xenial-updates/restricted i386 Packages [7,524 B]
Get:10 http://mirrors.linode.com/ubuntu xenial-updates/universe amd64 Packages [679 kB]
Get:11 http://mirrors.linode.com/ubuntu xenial-updates/universe i386 Packages [619 kB]
Get:12 http://mirrors.linode.com/ubuntu xenial-updates/universe Translation-en [273 kB]
Get:13 http://mirrors.linode.com/ubuntu xenial-updates/multiverse amd64 Packages [16.4 kB]
Get:14 http://mirrors.linode.com/ubuntu xenial-updates/multiverse i386 Packages [15.5 kB]
Get:15 http://mirrors.linode.com/ubuntu xenial-backports/main amd64 Packages [6,756 B]
Get:16 http://mirrors.linode.com/ubuntu xenial-backports/main i386 Packages [6,752 B]
Get:17 http://mirrors.linode.com/ubuntu xenial-backports/main Translation-en [4,180 B]
Get:18 http://mirrors.linode.com/ubuntu xenial-backports/universe amd64 Packages [7,420 B]
Get:19 http://mirrors.linode.com/ubuntu xenial-backports/universe i386 Packages [7,104 B]
Get:20 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [533 kB]
Get:21 http://security.ubuntu.com/ubuntu xenial-security/main i386 Packages [469 kB]
Get:22 http://security.ubuntu.com/ubuntu xenial-security/main Translation-en [228 kB]
Get:23 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [365 kB]
Get:24 http://security.ubuntu.com/ubuntu xenial-security/universe i386 Packages [311 kB]
Get:25 http://security.ubuntu.com/ubuntu xenial-security/universe Translation-en [137 kB]
Get:26 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [3,456 B]
Get:27 http://security.ubuntu.com/ubuntu xenial-security/multiverse i386 Packages [3,628 B]
Fetched 5,938 kB in 3s (1,513 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
software-properties-common is already the newest version (0.96.20.7).
0 upgraded, 0 newly installed, 0 to remove and 63 not upgraded.
gpg: keyring `/tmp/tmpi0snknnf/secring.gpg' created
gpg: keyring `/tmp/tmpi0snknnf/pubring.gpg' created
gpg: requesting key E5267A6C from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpi0snknnf/trustdb.gpg: trustdb created
gpg: key E5267A6C: public key "Launchpad PPA for Ondřej Surý" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
gpg: keyring `/tmp/tmpfax3c72u/secring.gpg' created
gpg: keyring `/tmp/tmpfax3c72u/pubring.gpg' created
gpg: requesting key C300EE8C from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpfax3c72u/trustdb.gpg: trustdb created
gpg: key C300EE8C: public key "Launchpad Stable" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
OK
OK
Hit:1 http://mirrors.linode.com/ubuntu xenial InRelease
Hit:2 http://mirrors.linode.com/ubuntu xenial-updates InRelease
Hit:3 http://mirrors.linode.com/ubuntu xenial-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu xenial-security InRelease
Ign:5 http://launchpad.proxy.ustclug.org/nginx/stable/ubuntu xenial InRelease
Ign:6 http://launchpad.proxy.ustclug.org/ondrej/php/ubuntu xenial InRelease
Ign:7 http://launchpad.proxy.ustclug.org/nginx/stable/ubuntu xenial Release
Ign:8 http://launchpad.proxy.ustclug.org/ondrej/php/ubuntu xenial Release
Ign:9 http://launchpad.proxy.ustclug.org/nginx/stable/ubuntu xenial/main amd64 Packages
Ign:10 http://launchpad.proxy.ustclug.org/nginx/stable/ubuntu xenial/main i386 Packages
Ign:11 http://launchpad.proxy.ustclug.org/nginx/stable/ubuntu xenial/main all Packages
Ign:12 http://launchpad.proxy.ustclug.org/nginx/stable/ubuntu xenial/main Translation-en_US
Ign:13 http://launchpad.proxy.ustclug.org/nginx/stable/ubuntu xenial/main Translation-en
Ign:14 http://launchpad.proxy.ustclug.org/ondrej/php/ubuntu xenial/main amd64 Packages
Ign:15 http://launchpad.proxy.ustclug.org/ondrej/php/ubuntu xenial/main i386 Packages
Ign:16 http://launchpad.proxy.ustclug.org/ondrej/php/ubuntu xenial/main all Packages
Ign:17 http://launchpad.proxy.ustclug.org/ondrej/php/ubuntu xenial/main Translation-en_US
Ign:18 http://launchpad.proxy.ustclug.org/ondrej/php/ubuntu xenial/main Translation-en
Ign:9 http://launchpad.proxy.ustclug.org/nginx/stable/ubuntu xenial/main amd64 Packages
Ign:10 http://launchpad.proxy.ustclug.org/nginx/stable/ubuntu xenial/main i386 Packages
Ign:11 http://launchpad.proxy.ustclug.org/nginx/stable/ubuntu xenial/main all Packages
Ign:12 http://launchpad.proxy.ustclug.org/nginx/stable/ubuntu xenial/main Translation-en_US
Ign:13 http://launchpad.proxy.ustclug.org/nginx/stable/ubuntu xenial/main Translation-en
Ign:14 http://launchpad.proxy.ustclug.org/ondrej/php/ubuntu xenial/main amd64 Packages
Ign:15 http://launchpad.proxy.ustclug.org/ondrej/php/ubuntu xenial/main i386 Packages
Ign:16 http://launchpad.proxy.ustclug.org/ondrej/php/ubuntu xenial/main all Packages
Ign:17 http://launchpad.proxy.ustclug.org/ondrej/php/ubuntu xenial/main Translation-en_US
Ign:18 http://launchpad.proxy.ustclug.org/ondrej/php/ubuntu xenial/main Translation-en
Ign:9 http://launchpad.proxy.ustclug.org/nginx/stable/ubuntu xenial/main amd64 Packages
Ign:10 http://launchpad.proxy.ustclug.org/nginx/stable/ubuntu xenial/main i386 Packages
Ign:11 http://launchpad.proxy.ustclug.org/nginx/stable/ubuntu xenial/main all Packages
Ign:12 http://launchpad.proxy.ustclug.org/nginx/stable/ubuntu xenial/main Translation-en_US
Ign:13 http://launchpad.proxy.ustclug.org/nginx/stable/ubuntu xenial/main Translation-en
Ign:14 http://launchpad.proxy.ustclug.org/ondrej/php/ubuntu xenial/main amd64 Packages
Ign:15 http://launchpad.proxy.ustclug.org/ondrej/php/ubuntu xenial/main i386 Packages
Ign:16 http://launchpad.proxy.ustclug.org/ondrej/php/ubuntu xenial/main all Packages
Ign:17 http://launchpad.proxy.ustclug.org/ondrej/php/ubuntu xenial/main Translation-en_US
Ign:18 http://launchpad.proxy.ustclug.org/ondrej/php/ubuntu xenial/main Translation-en
Ign:9 http://launchpad.proxy.ustclug.org/nginx/stable/ubuntu xenial/main amd64 Packages
Ign:10 http://launchpad.proxy.ustclug.org/nginx/stable/ubuntu xenial/main i386 Packages
Ign:11 http://launchpad.proxy.ustclug.org/nginx/stable/ubuntu xenial/main all Packages
Ign:12 http://launchpad.proxy.ustclug.org/nginx/stable/ubuntu xenial/main Translation-en_US
Ign:13 http://launchpad.proxy.ustclug.org/nginx/stable/ubuntu xenial/main Translation-en
Ign:14 http://launchpad.proxy.ustclug.org/ondrej/php/ubuntu xenial/main amd64 Packages
Ign:15 http://launchpad.proxy.ustclug.org/ondrej/php/ubuntu xenial/main i386 Packages
Ign:16 http://launchpad.proxy.ustclug.org/ondrej/php/ubuntu xenial/main all Packages
Ign:17 http://launchpad.proxy.ustclug.org/ondrej/php/ubuntu xenial/main Translation-en_US
Ign:18 http://launchpad.proxy.ustclug.org/ondrej/php/ubuntu xenial/main Translation-en
Ign:9 http://launchpad.proxy.ustclug.org/nginx/stable/ubuntu xenial/main amd64 Packages
Ign:10 http://launchpad.proxy.ustclug.org/nginx/stable/ubuntu xenial/main i386 Packages
Ign:11 http://launchpad.proxy.ustclug.org/nginx/stable/ubuntu xenial/main all Packages
Ign:12 http://launchpad.proxy.ustclug.org/nginx/stable/ubuntu xenial/main Translation-en_US
Ign:13 http://launchpad.proxy.ustclug.org/nginx/stable/ubuntu xenial/main Translation-en
Ign:14 http://launchpad.proxy.ustclug.org/ondrej/php/ubuntu xenial/main amd64 Packages
Ign:15 http://launchpad.proxy.ustclug.org/ondrej/php/ubuntu xenial/main i386 Packages
Ign:16 http://launchpad.proxy.ustclug.org/ondrej/php/ubuntu xenial/main all Packages
Ign:17 http://launchpad.proxy.ustclug.org/ondrej/php/ubuntu xenial/main Translation-en_US
Ign:18 http://launchpad.proxy.ustclug.org/ondrej/php/ubuntu xenial/main Translation-en
Err:9 http://launchpad.proxy.ustclug.org/nginx/stable/ubuntu xenial/main amd64 Packages
  Connection failed
Ign:10 http://launchpad.proxy.ustclug.org/nginx/stable/ubuntu xenial/main i386 Packages
Ign:11 http://launchpad.proxy.ustclug.org/nginx/stable/ubuntu xenial/main all Packages
Ign:12 http://launchpad.proxy.ustclug.org/nginx/stable/ubuntu xenial/main Translation-en_US
Ign:13 http://launchpad.proxy.ustclug.org/nginx/stable/ubuntu xenial/main Translation-en
Err:14 http://launchpad.proxy.ustclug.org/ondrej/php/ubuntu xenial/main amd64 Packages
  Connection failed
Ign:15 http://launchpad.proxy.ustclug.org/ondrej/php/ubuntu xenial/main i386 Packages
Ign:16 http://launchpad.proxy.ustclug.org/ondrej/php/ubuntu xenial/main all Packages
Ign:17 http://launchpad.proxy.ustclug.org/ondrej/php/ubuntu xenial/main Translation-en_US
Ign:18 http://launchpad.proxy.ustclug.org/ondrej/php/ubuntu xenial/main Translation-en

以上是/var/log/laravel-ubuntu-init.log的内容

**Comment by leo108** [comment]
@Tex007  这个脚本是针对国内服务器优化的，软件源都是选择国内镜像或者代理，在国外服务器出现连接失败的情况是正常的

**Comment by Tex007** [comment]
好的,请问之前的那个ubuntu14的不维护了么
https://laravel-china.org/topics/2814/ubuntu-1416-under-the-laravel-lnmp-online-environment-automatically-deploy-scripts
这个命令提示404
wget https://raw.githubusercontent.com/summerblue/laravel-ubuntu-init/master/deploy.sh

**Comment by leo108** [comment]
@Tex007 不维护了

**Comment by Tex007** [comment]
小哥,ubuntu14的deploy.sh能否发我一份,用惯了之前配置好的服务器,自己安装的都不习惯了......
邮箱:635877517@qq.com
