### ISSUE TITLE
正在初始化软件源  自動結束了

### ISSUE THREAD

**Issue by WingCH** [summerblue/laravel-ubuntu-init#28]
![image](https://user-images.githubusercontent.com/19588517/67161678-56952a80-f38f-11e9-9cba-4ad432fed10c.png)

**Comment by leo108** [comment]
把 `/var/log/laravel-ubuntu-init.log` 这个文件内容贴出来，看看是否有报错

**Comment by WingCH** [comment]
我安裝完https://lnmp.org/download.html 之後再試一次

同樣也是突然停止
![image](https://user-images.githubusercontent.com/19588517/67209982-e21fc180-f44a-11e9-9942-c23f4e590508.png)

附上log檔
[laravel-ubuntu-init.log](https://github.com/summerblue/laravel-ubuntu-init/files/3751077/laravel-ubuntu-init.log)

感謝你的幫忙

**Comment by leo108** [comment]
看起来是和已经安装的 Nginx 冲突了，本脚本只支持在干净的服务器上安装。
