### ISSUE TITLE
请问支持 ubuntu 18.04 吗？

### ISSUE THREAD

**Issue by levelooy** [summerblue/laravel-ubuntu-init#29]
我试了下，其他都正常，就是安装 redis 的时候报错了：
````
Errors were encountered while processing:
 redis-server
 redis
E: Sub-process /usr/bin/dpkg returned an error code (1)
````

用的是阿里云服务器，更换为 ubuntu-16.04 的话，是没问题的

**Comment by leo108** [comment]
ubuntu 18.04 里的 redis 默认配置使用的 ipv6 地址，目前阿里云并没有默认开通 ipv6，所以会在安装 Redis 的过程中就会失败，暂时没有找到解决方案，所以无法支持。

**Comment by levelooy** [comment]
那么可以修改下 redis 的默认配置吗？
