### ISSUE TITLE
安装elasticserach7需要java11的jdk

### ISSUE THREAD

**Issue by wcx929** [summerblue/laravel-ubuntu-init#33]
<b>future versions of Elasticsearch will require Java 11; your Java version from [/usr/lib/jvm/java-8-openjdk-amd64/jre] does not meet this requirement
</b>

脚本里只有java8的jdk，导致es无法安装

**Comment by wcx929** [comment]
但是最后还是装上了，不知道为什么

**Comment by leo108** [comment]
这个句本来就是说**未来版本**的 ES 需要 Java11

**Comment by wcx929** [comment]
> 这个句本来就是说**未来版本**的ES需要Java11

谢谢解答，原本装的es6 因为本地是es7 结果服务器升级的时候出了问题，现在已经解决了。

漏看了future，英语不太好。,谢谢您的解答
